name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - uses: safe-research/actions/install-just@v1

      - run: just check
      - run: just test
